FROM node:lts-slim
RUN apt-get update -y
RUN apt-get install -y openssl

WORKDIR /app
COPY package.json .
COPY package-lock.json .
COPY ./prisma .
RUN npm install
RUN npx prisma migrate
COPY build ./build
EXPOSE 3000
CMD ["node", "./build/websocket-server/index.js"]