FROM node:lts-slim
RUN apt-get update -y
RUN apt-get install -y openssl

WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY ./prisma .
RUN npx prisma generate
COPY build ./build
EXPOSE 3000
CMD ["node", "./build/main-server/index.js"]